In [9]:
import torch


x = torch.tensor([0, 1, 2, 3])
x

tensor([0, 1, 2, 3])

In [10]:
def f(x):
    return x**2

def loss(pred, target):
    return (pred - target).pow(2).sum()

target = f(x)
target

tensor([0, 1, 4, 9])

In [11]:
w = torch.randn(4, requires_grad=True)
w

tensor([ 0.4129, -0.6857, -0.1868,  1.0024], requires_grad=True)

In [16]:
learningRate = 0.1
for i in range(0, 10):
    pred = x * w
    print('***********************\n')
    print(f'Pred : {pred}')
    l = loss(pred, target)
    print(f'Loss : {l}')
    l.backward()
    with torch.no_grad():
        w -= learningRate * w.grad
        print(f'New weights : {w}')
        w.grad.zero_()
pred

***********************

Pred : tensor([0.0000, 0.8781, 3.9999, 9.0000], grad_fn=<MulBackward0>)
Loss : 0.014871264807879925
New weights : tensor([0.4129, 0.9024, 2.0000, 3.0000], requires_grad=True)
***********************

Pred : tensor([0.0000, 0.9024, 4.0000, 9.0000], grad_fn=<MulBackward0>)
Loss : 0.009517602622509003
New weights : tensor([0.4129, 0.9220, 2.0000, 3.0000], requires_grad=True)
***********************

Pred : tensor([0.0000, 0.9220, 4.0000, 9.0000], grad_fn=<MulBackward0>)
Loss : 0.006091265473514795
New weights : tensor([0.4129, 0.9376, 2.0000, 3.0000], requires_grad=True)
***********************

Pred : tensor([0.0000, 0.9376, 4.0000, 9.0000], grad_fn=<MulBackward0>)
Loss : 0.0038984084967523813
New weights : tensor([0.4129, 0.9501, 2.0000, 3.0000], requires_grad=True)
***********************

Pred : tensor([0.0000, 0.9501, 4.0000, 9.0000], grad_fn=<MulBackward0>)
Loss : 0.00249497895129025
New weights : tensor([0.4129, 0.9600, 2.0000, 3.0000], requires_grad=True)


tensor([0.0000, 0.9836, 4.0000, 9.0000], grad_fn=<MulBackward0>)

In [17]:
xv = torch.tensor([5])

xv * w

tensor([ 2.0643,  4.9345, 10.0000, 15.0000], grad_fn=<MulBackward0>)